
services:

  app:
    container_name: gestion-recipes-api-app
    image: recipes
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    depends_on:
      - db
    env_file:
      - .env
     
    
    
  db:
    image: mysql
    container_name: recipes_mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3308:3306"
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: