
version: '3.8'

services:
  db:
    env_file: .env
    image: mysql
    container_name: gestion-recipes-api
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '3309:3306'

  app:
    env_file: .env
    image: gestion-recipes-api-app
    container_name: gestion-recipes-api-app
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    ports:
      - '3070:3070'
    depends_on:
      - db
volumes:
  db-data: